version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root_username
      - MONGO_INITDB_ROOT_PASSWORD=root_password

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root_username
      ME_CONFIG_MONGODB_ADMINPASSWORD: root_password


volumes:
  data: {}
networks:
  default:
    name: mongodb_network